name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Lua
        uses: leafo/gh-actions-lua@v8

      - name: Install Luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Extract tag name
        id: tag_env
        shell: bash
        run: echo "##[set-output name=version;]$(echo ${GITHUB_REF##*/})"

      # use ${tag:1} to filter out the heading "v" of "v1.0" 
      - name: Upload to luarocks
        env:
          LUAROCKS_TOKEN: ${{ secrets.LUAROCKS_TOKEN }}
        run: |
          luarocks install dkjson
          tag=${{ steps.tag_env.outputs.version }}
          luarocks upload rockspec/lua-resty-etcd-${tag:1}-0.rockspec --api-key=${LUAROCKS_TOKEN}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_env.outputs.version }}
          release_name: ${{ steps.tag_env.outputs.version }}
          draft: false
          prerelease: false
